using System;


using System.Collections;
using System.Collections.Generic;
using System.Linq;

using System.Reflection;
using SObject = System.Object;

using D = System.Diagnostics.Debug;
using MG = MainGrammar.MainGrammar;
using MGRX = MainGrammar.MainGrammarRX;
using NLSPlain;

using ParserComb;

//#if !mock_NamedNode_Types
using SuggestionTree;
using SGA = SuggestionTree.SuggTAdapter;
//#endif




using UnityEngine;




namespace TranslateAndEval {

 

        public class TestSG_TU : TranslationUnit { 
            public override VBoxTU[] VBoxTUs => throw new NotImplementedException();

            public override IEnumerable<OPCode> emit ()                   => throw new NotImplementedException();
            public override preCH_deltaScope    scope(preCH_deltaScope c) => c ; // no decls or refs possible 

            public preCH pre_CH_out ; 
            TypeFilterVBX_TU typefilter = null;


            public TestSG_TU ( MG.SG_EdgeNode edgeNode , preCH preCH_in ) {
                if ( edgeNode.typefilter != null ) {
                    typefilter = new TypeFilterVBX_TU ( preCH_in ,  edgeNode.typefilter  );
                    pre_CH_out = typefilter.preCH_out;
                } else {
                    pre_CH_out = new deferred_adapter_preCH ( ()=> preCH_in.CH );
                }
                // plug in delegate in both cases
            }

        }

        /*
            assuming the scoping process never needs to access VBoxTUs ... 
        */
        public abstract class TU_RX : TranslationUnit
        {
            // again, this is a hack, reverse inheritance arrow later 
            public override VBoxTU[]            VBoxTUs => throw new NotImplementedException();
            public override IEnumerable<OPCode> emit()  => throw new NotImplementedException();
        }

     

        public class FanElemRX_TU : TU_RX
        {
            public TranslationUnit [] subTUs;
            public preCH preCH_out;
            public FanElemRX_TU ( MG.FanElemNode fanElemNode , preCH preCH_in  ) { 
                var _subTUs = new List<TranslationUnit>();
                var loop_preCH = preCH_in;
                foreach ( NamedNode nn in fanElemNode.children ) { 
                    if ( nn is MG.RG_EdgeNode ) { // and thus implicitly generated by RG_Edge_RX, atm it reuses the normal RG_EdgeNode
                        var rg_edgeTU = new RG_EdgeTU_RX( (MG.RG_EdgeNode) nn , loop_preCH ) ;
                        _subTUs.Add(  rg_edgeTU);
                        loop_preCH = rg_edgeTU.preCH_out ;
                    } else throw new NotImplementedException();
                }
                preCH_out = loop_preCH;
                subTUs = _subTUs.ToArray();
            }
            public override preCH_deltaScope scope(preCH_deltaScope c)
            {
                foreach( var sTU in subTUs ) c = sTU.scope(c );
                return c;
            }
        }

        public class RG_EdgeTU_RX : TU_RX
        {
            public readonly preCH preCH_out;
            public readonly Assign_VBXTU assignVTNode = null ;

            public RG_EdgeTU_RX ( MG.RG_EdgeNode rg_EdgeNode , preCH preCH_in ) {
                var memANodeRX = (MGRX.MemANodeRX)rg_EdgeNode.memAVT.children[0];  // todo proper field in MemAVTNode - hard cast doubles as Assert
                memANodeRX.ACMembTypingCallback = () => preCH_in.PayT;
                // for now, and for lazyness: no extra TU_RX for MemARX 
                var memA_preCH_out = new deferred_preCH ( 
                    ()=> { 
                        return new TTuple { 
                            isMulti = false , // todo 
                            PayT    = SGA.MembType_Exact( preCH_in.PayT , memANodeRX.name )
                            };
                        }, 
                    dataSrc: null // not used in RX-case 
                    );

                // todo Assign creates a new Column ( thus distinct preCH ) in the properly translated version 
                // the proper preCH out is that of AssignVT - but since types are identical, and that's all we care for here : this could simply be dropped, but i need the assignVTNode for scoping 

                if ( rg_EdgeNode.assignVT == null ) {
                    preCH_out = memA_preCH_out;    
                } else { 
                    assignVTNode = new Assign_VBXTU(preCH_in , rg_EdgeNode.assignVT );
                    preCH_out = assignVTNode.preCH_out;
                }

            }
            public override preCH_deltaScope scope(preCH_deltaScope c)
            {
                // piggyback the scoping on nonRX variant? 
                if ( assignVTNode != null ) return assignVTNode.scope(c);
                return c;
            }
        }

    public class MemA_VBX_TU_RX : MemA_VBXTU { 
        public MemA_VBX_TU_RX ( preCH preCH_in , MGRX.MemANodeRX memA_node_rx ) : base ( preCH_in , memA_node_rx ) {
            memA_node_rx.ACMembTypingCallback = () => 
                preCH_in.PayT;
        }
    }
    
    public class PrimitveStepTU_RX : PrimitveStepTU {
        public PrimitveStepTU_RX ( preCH preCH_in , MGRX.PrimitiveStepNode prim_step_node )  {
            // pretty fucky - copy and paste job from the nonRX variant - needed though to plug in the RX constructors for child TUs
            this.primtv_step_node = prim_step_node;       //
            var primaryNN = primtv_step_node.children[0];
            if        ( primaryNN is MG.SG_EdgeNode ) {

                primaryTU           = new SG_EdgeTU( preCH_in , (MG.SG_EdgeNode) primaryNN ) ;
                primary_preCH_out   = ((SG_EdgeTU) primaryTU).preCH_out;

            } else if ( primaryNN is MG.MemANode ) {
                var MemTU = new MemA_VBX_TU_RX(preCH_in , (MGRX.MemANodeRX) primaryNN) ;          //  type - patch I
                primaryTU = MemTU;
                primary_preCH_out = MemTU.preCH_out;
            
            } else if ( primaryNN is MG.FilterNode ) {
                var filterTU = new FilterTU( preCH_in , (MG.FilterNode) primaryNN );
                primaryTU = filterTU;
                primary_preCH_out = filterTU.preCH_out;
            } else if ( primaryNN is MG.FanNode ) {
                var fanTU = new FanTU( preCH_in , (MG.FanNode) primaryNN) ;
                primaryTU = fanTU;
                primary_preCH_out = fanTU.pRHS;
            } else throw new Exception();  // grammar changed or parser bug 

            preCH current_preCH_out = primary_preCH_out;
            foreach( var asgn_node in primtv_step_node.assigns) {
                var asgn_TU = new Assign_VBXTU( current_preCH_out , asgn_node );
                assigns.Add( asgn_TU);
                current_preCH_out = asgn_TU.preCH_out;
            }
            preCH_out = current_preCH_out; 
        }
    }
    
    public class ProvStartTU_RX : ProvStartTU
    {
        public ProvStartTU_RX ( MGRX.ProvStartNode start_N ) {
            root_SG_edge = new Root_SG_EdgeTU( start_N.startSG );  // todo, 
            preCH current_preCH = root_SG_edge.preCH_out ;
            var L = new List<PrimitveStepTU>();
            foreach ( var prim_step in start_N.primSteps ) {
                var TU = new PrimitveStepTU_RX(current_preCH , prim_step  );
                current_preCH = TU.preCH_out;
                L.Add ( TU ) ;
            }
            prim_Steps = L.ToArray();
        }
        /*
        public override preCH_deltaScope scope(preCH_deltaScope c)
        {
            throw new NotImplementedException();
        }
        */
    }



}